name: Automatisation des tests

on: push

jobs:
  # 1) Compilation une seule fois
  compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure & Build
        run: |
          cmake -S . -B build
          cmake --build build --config Release -j 2

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/**
          if-no-files-found: error

  # 2) Tests en parallèle
  test_add:
    runs-on: ubuntu-latest
    needs: compilation
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Test fonction add
        run: |
          chmod +x build/src/calculator
          ./build/src/calculator add 10 5

  test_sub:
    runs-on: ubuntu-latest
    needs: compilation
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Test fonction sub
        run: |
          chmod +x build/src/calculator
          ./build/src/calculator sub 10 5

  test_mul:
    runs-on: ubuntu-latest
    needs: compilation
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Test fonction mul
        run: |
          chmod +x build/src/calculator
          ./build/src/calculator mul 10 5

  test_div:
    runs-on: ubuntu-latest
    needs: compilation
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Test fonction div
        run: |
          chmod +x build/src/calculator
          ./build/src/calculator div 10 5

  # 3) Déploiement après tous les tests
  deployment:
    runs-on: ubuntu-latest
    needs: [test_add, test_sub, test_mul, test_div]
    steps:
      - name: Déploiement
        run: echo "Déploiement de la solution"
